### ISSUE TITLE
npm run download_snapshot error

### ISSUE THREAD

**Issue by napster3000** [0xProject/wiki#23]
I got an error if I run
"npm run download_snapshot"

```
 download --extract --strip 1 --out 0x_testrpc_snapshot ${npm_package_config_snapshot_url}
HTTPError: Response code 404 (Not Found)
```

but if i change manually the url in package.json, it works

```
"scripts": {
    "build": "tsc",
    "dev": "npm run build; node ./lib/index.js",
    "clean": "shx rm -rf _bundles lib",
    "lint": "tslint src/**/*.ts",
    "download_snapshot": "download --extract --strip 1 --out 0x_testrpc_snapshot https://s3.amazonaws.com/testrpc-shapshots/35053f9.zip",
    "testrpc": "testrpc -p 8545 --networkId 50 --db ./0x_testrpc_snapshot -m \"${npm_package_config_mnemonic}\""
  },
```

**Comment by themandalore** [comment]
Can confirm...great job figuring out a work around btw

**Comment by fabioberger** [comment]
@themandalore what is the root of this issue? I'm unable to repro.

**Comment by themandalore** [comment]
My guess is that it's a windows issue, but I really have no idea.  I just know that I don't get the error when I run it with the updated  link

**Comment by fabioberger** [comment]
Thanks @themandalore. @napster3000 were you able to figure out the root of the issue?
