### ISSUE TITLE
Web3 version should be specified

### ISSUE THREAD

**Issue by riteable** [0xProject/wiki#4]
0x.js doesn't seem to work with web3 1.0.0. I remember this being mentioned in the docs, but it's not there anymore. There should be a notice that web3 0.19.0 should be used at the moment. I just spent the whole evening pulling my hair out, when I suddenly remembered that caveat.

**Comment by fabioberger** [comment]
@riteable 0x.js V0.12.1 and above support Web3 V1.0 Beta providers and that's why we removed the comment. We could add it back with the version specifics. Were you using an earlier version on 0x.js?

**Comment by fabioberger** [comment]
Added a comment about this: https://github.com/0xProject/wiki/commit/40cdfd721270c82ee9aa3130f3e90037db4420de
