### ISSUE TITLE
add support other Languages.

### ISSUE THREAD

**Issue by EvertonMelo** [0xProject/wiki#48]
what would be the best way to translate this wiki?

**Comment by fabioberger** [comment]
Hey @EvertonMelo, thanks for the suggestion. If you want to contribute to that, I'd open a PR moving all the existing content into a `en` folder and adding other language folders. 

I am concerned about keeping translations up-to-date as things evolve. Quite a few articles will require heavy editing once V2 launches. Should we potentially plan on translating once V2 launches?

**Comment by EvertonMelo** [comment]
@fabioberger 
thank you for the feedback.

I can make a structure similar to the BIP001 of btc core.

1º clone repositora 
2º change for Portuguese
3º PR - l18n - All files,  

what do you think about this?

I'm doing this in some places:
https://github.com/NemProject/NIP/pull/1
https://github.com/input-output-hk/cardanodocs.com/pull/94
https://github.com/bitcoin/bips/pull/653

I'm glad you thought big.

**Comment by fabioberger** [comment]
@EvertonMelo at this time I feel translation would be premature. V2 of 0x protocol is coming out in a few months and require heavy editing of these wiki articles. 

Let's please touch base once V2 launches.

Thanks again for offering to help. Obrigado!

**Comment by EvertonMelo** [comment]
Okay. 
It will be a pleasure to help.
